
import __ASTRO_IMAGE_IMPORT_Z2qvE9t from "/src/images/blog/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F1.md";
import __ASTRO_IMAGE_IMPORT_Z2qvw96 from "/src/images/blog/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2.md";
import __ASTRO_IMAGE_IMPORT_Z2qvo8I from "/src/images/blog/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F3.md";
import __ASTRO_IMAGE_IMPORT_Z2qvg8l from "/src/images/blog/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F4.md";
import __ASTRO_IMAGE_IMPORT_Z2qv87X from "/src/images/blog/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F5.md";
import __ASTRO_IMAGE_IMPORT_Z2qv07A from "/src/images/blog/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F6.md";
import __ASTRO_IMAGE_IMPORT_7WUYq from "/src/images/trusted/mike-andreuzza.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fmembers%2Fmichael-andreuzza.md";
import __ASTRO_IMAGE_IMPORT_fOOcL from "/src/images/trusted/robert-austin.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fmembers%2Frobert-austin.md";
export default new Map([["/src/images/blog/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F1.md", __ASTRO_IMAGE_IMPORT_Z2qvE9t], ["/src/images/blog/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F2.md", __ASTRO_IMAGE_IMPORT_Z2qvw96], ["/src/images/blog/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F3.md", __ASTRO_IMAGE_IMPORT_Z2qvo8I], ["/src/images/blog/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F4.md", __ASTRO_IMAGE_IMPORT_Z2qvg8l], ["/src/images/blog/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F5.md", __ASTRO_IMAGE_IMPORT_Z2qv87X], ["/src/images/blog/1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2F6.md", __ASTRO_IMAGE_IMPORT_Z2qv07A], ["/src/images/trusted/mike-andreuzza.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fmembers%2Fmichael-andreuzza.md", __ASTRO_IMAGE_IMPORT_7WUYq], ["/src/images/trusted/robert-austin.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fmembers%2Frobert-austin.md", __ASTRO_IMAGE_IMPORT_fOOcL]]);
		